### ISSUE TITLE
Admin Add Booking Page Broken

### ISSUE THREAD

**Issue by ghost** [LiamBailey/woo-bookings-dropdown#1]
![screen shot 2019-02-13 at 11 33 43 am](https://user-images.githubusercontent.com/35930782/52727485-52ed1080-2f83-11e9-8ad0-ff2c154c1032.png)

**WOO-BOOKINGS: Version 1.13.1** 

LOG
------------
2019-02-13T16:05:07+00:00 CRITICAL Uncaught Error: Call to a member function get_availability_rules() on null in /srv/users/serverpilot/apps/worksite/current/wp-content/plugins/woo-bookings-dropdown/woo-bookings-dropdown.php:89
Stack trace:
#0 /srv/users/serverpilot/apps/worksite/current/wp-includes/class-wp-hook.php(286): wswp_booking_form_fields(Array)
#1 /srv/users/serverpilot/apps/worksite/current/wp-includes/plugin.php(203): WP_Hook->apply_filters(Array, Array)
#2 /srv/users/serverpilot/apps/worksite/current/wp-content/plugins/woocommerce-bookings/includes/booking-form/class-wc-booking-form.php(170): apply_filters('booking_form_fi...', Array)
#3 /srv/users/serverpilot/apps/worksite/current/wp-content/plugins/woocommerce-bookings/includes/booking-form/class-wc-booking-form.php(427): WC_Booking_Form->prepare_fields()
#4 /srv/users/serverpilot/apps/worksite/current/wp-content/plugins/woocommerce-bookings/includes/admin/views/html-create-booking-page-2.php(20): WC_Booking_Form->output()
#5 /srv/users/serverpilot/apps/worksite/current/wp-conte in /srv/users/serverpilot/apps/worksite/current/wp-content/plugins/woo-bookings-dropdown/woo-bookings-dropdown.php on line 89

**Comment by LiamBailey** [comment]
Hi - I don't see this error on my install, it could be a problem with another plugin or something in the theme causing the product to be null. In any case I don't think the WC Booking Form class is usually invoked in the admin screens. Can you tell me what versions of WooCommerce, WooCommerce Bookings, and WP you are on? That said I am pushing a new release today, I will make it so my code only runs on the frontend that should solve your problem
